export enum PlayerAction {
  GATHER_RESOURCE = 'GATHER_RESOURCE',
  USE_RESOURCE = 'USE_RESOURCE',
  BOND_COMPANION = 'BOND_COMPANION',
  CRAFT_ITEM = 'CRAFT_ITEM',
  USE_ITEM = 'USE_ITEM',
  FACE_CHALLENGE = 'FACE_CHALLENGE',
  USE_ABILITY = 'USE_ABILITY',
  REST = 'REST',
  EXPLORE = 'EXPLORE',
  PREVENT_THREAT = 'PREVENT_THREAT'
}
