export enum CardType {
  CHARACTER = 'CHARACTER',
  LANDSCAPE = 'LANDSCAPE',
  ANIMAL_COMPANION = 'ANIMAL_COMPANION',
  RESOURCE = 'RESOURCE',
  CRAFTED_ITEM = 'CRAFTED_ITEM',
  SEASON = 'SEASON',
  ACTION = 'ACTION',
  WARNING = 'WARNING',
  SUCCESS = 'SUCCESS',
  DANGER = 'DANGER',
  STORY = 'STORY'
}

export enum ChallengeType {
  STRENGTH = 'STRENGTH',
  WISDOM = 'WISDOM',
  AGILITY = 'AGILITY',
  DIPLOMACY = 'DIPLOMACY',
  SURVIVAL = 'SURVIVAL'
}
